base_url = "https://ericscouten.studio"

title = "Eric Scouten :: Studio"
description = "Occasional thoughts on photography."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
es_site = "studio"
