base_url = "https://ericscouten.studio"

title = "Eric Scouten :: Studio"
description = "Occasional thoughts on photography."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feeds = true
feed_filenames = ["rss.xml"]

[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
endmark = true
es_site = "studio"
article_type = "thoughts on photography"
fathom_site_id = "LOTHNSVD"
section_reverse_default = true
comments_enabled_default = false
